In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from xgboost import XGBRFRegressor
from sklearn.svm import SVR

In [3]:
data=pd.read_csv('car details v4.csv')
data.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                2059 non-null   str
 1   Model               2059 non-null   str
 2   Price               2059 non-null   int64
 3   Year                2059 non-null   int64
 4   Kilometer           2059 non-null   int64
 5   Fuel Type           2059 non-null   str
 6   Transmission        2059 non-null   str
 7   Location            2059 non-null   str
 8   Color               2059 non-null   str
 9   Owner               2059 non-null   str
 10  Seller Type         2059 non-null   str
 11  Engine              1979 non-null   str
 12  Max Power           1979 non-null   str
 13  Max Torque          1979 non-null   str
 14  Drivetrain          1923 non-null   str
 15  Length              1995 non-null   float64
 16  Width               1995 non-null   float64
 17  Height              1995 non-null   float64
 18  Seating Capacity    1995 non-null   float64
 19  Fuel Tank Capacity  1946 non-null   float64
dtypes: float64(5), int64(3), str(12)
memory usage: 545.4 KB

In [5]:
data.describe()

,Price,Year,Kilometer,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
count,2.059000e+03,2059.000000,2.059000e+03,1995.000000,1995.000000,1995.000000,1995.000000,1946.000000
mean,1.702992e+06,2016.425449,5.422471e+04,4280.860652,1767.991980,1591.735338,5.306266,52.002210
std,2.419881e+06,3.363564,5.736172e+04,442.458507,135.265825,136.073956,0.822170,15.110198
min,4.900000e+04,1988.000000,0.000000e+00,3099.000000,1475.000000,1165.000000,2.000000,15.000000
25%,4.849990e+05,2014.000000,2.900000e+04,3985.000000,1695.000000,1485.000000,5.000000,41.250000
50%,8.250000e+05,2017.000000,5.000000e+04,4370.000000,1770.000000,1545.000000,5.000000,50.000000
75%,1.925000e+06,2019.000000,7.200000e+04,4629.000000,1831.500000,1675.000000,5.000000,60.000000
max,3.500000e+07,2022.000000,2.000000e+06,5569.000000,2220.000000,1995.000000,8.000000,105.000000

In [6]:
data.dropna(inplace=True)

In [7]:
data.info()

<class 'pandas.DataFrame'>
Index: 1874 entries, 0 to 2057
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                1874 non-null   str
 1   Model               1874 non-null   str
 2   Price               1874 non-null   int64
 3   Year                1874 non-null   int64
 4   Kilometer           1874 non-null   int64
 5   Fuel Type           1874 non-null   str
 6   Transmission        1874 non-null   str
 7   Location            1874 non-null   str
 8   Color               1874 non-null   str
 9   Owner               1874 non-null   str
 10  Seller Type         1874 non-null   str
 11  Engine              1874 non-null   str
 12  Max Power           1874 non-null   str
 13  Max Torque          1874 non-null   str
 14  Drivetrain          1874 non-null   str
 15  Length              1874 non-null   float64
 16  Width               1874 non-null   float64
 17  Height              1874 non-null   float64
 18  Seating Capacity    1874 non-null   float64
 19  Fuel Tank Capacity  1874 non-null   float64
dtypes: float64(5), int64(3), str(12)
memory usage: 517.5 KB

In [8]:
X=data.drop('Price',axis=1)
y=data['Price']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [9]:
c = data.dtypes == "object"

categorical_columns = list(c[c==True].index)
print(f"categorical columns are: {categorical_columns}")

numerical_columns = list(c[c==False].index)
print(f"\nnumerical columns are: {numerical_columns}")

categorical columns are: []

numerical columns are: ['Make', 'Model', 'Price', 'Year', 'Kilometer', 'Fuel Type', 'Transmission', 'Location', 'Color', 'Owner', 'Seller Type', 'Engine', 'Max Power', 'Max Torque', 'Drivetrain', 'Length', 'Width', 'Height', 'Seating Capacity', 'Fuel Tank Capacity']

In [10]:
numer_trans=Pipeline(
    steps=[
        ('Imputer',SimpleImputer(strategy='mean')),
        ('Scalar',StandardScaler())
    ]
)
cat_trans=Pipeline(steps=[
    ('Imputer',SimpleImputer(strategy='most_frequent')),
    ('Onhot',OneHotEncoder(sparse_output=False,handle_unknown='ignore')),
    ('Scalar',StandardScaler())
])

In [11]:
preprocessing=ColumnTransformer(
    transformers=[
        ('numer_tans',numer_trans,[ 'Year', 'Kilometer', 'Length', 'Width', 'Height', 'Seating Capacity', 'Fuel Tank Capacity']),
        ('cat_trans',cat_trans,['Make', 'Model', 'Fuel Type', 'Transmission', 'Location', 'Color', 'Owner', 'Seller Type', 'Engine', 'Max Power', 'Max Torque', 'Drivetrain'])
    ]
)

In [12]:
algorithms={
    'Linear_Regression':LinearRegression(),
    'Random_Forest_Regressor':RandomForestRegressor(),
    'Xgboost':XGBRegressor(),
    'Xgbrfregressor':XGBRFRegressor(),
    "Descion_Tree":DecisionTreeRegressor(),
    'K_Nearest':KNeighborsRegressor(),
     "SVR":SVR()
}

In [13]:
for i,j in algorithms.items():
    model=Pipeline(
        steps=[
            ('Preprocessing',preprocessing), 
            (i,j)
        ]
    )
    model.fit(X_train,y_train)
    print(i)
    print(f'The training score is {model.score(X_train,y_train)}')
    print(f'The testing score is {model.score(X_test,y_test)}')

Linear_Regression
The training score is 0.9859326018070563
The testing score is -5.591671009603071
Random_Forest_Regressor
The training score is 0.9754976083813696
The testing score is 0.6481633011502959
Xgboost
The training score is 0.9975736737251282
The testing score is 0.645148754119873
Xgbrfregressor
The training score is 0.9444120526313782
The testing score is 0.6171694993972778
Descion_Tree
The training score is 0.9997406170871133
The testing score is 0.6209012188453724
K_Nearest
The training score is 0.5774024386905983
The testing score is 0.15621506465521318
SVR
The training score is -0.14379324129552828
The testing score is -0.1159161464065297

In [14]:
model=Pipeline(
    steps=[
        ('Preprocessing',preprocessing),
        ('Linear_Regression',RandomForestRegressor())  # Add regularization term
    ]
)

In [15]:
model.fit(X_train,y_train)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('numer_tans',
                                                  Pipeline(steps=[('Imputer',
                                                                   SimpleImputer()),
                                                                  ('Scalar',
                                                                   StandardScaler())]),
                                                  ['Year', 'Kilometer',
                                                   'Length', 'Width', 'Height',
                                                   'Seating Capacity',
                                                   'Fuel Tank Capacity']),
                                                 ('cat_trans',
                                                  Pipeline(steps=[('Imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('Onhot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False)),
                                                                  ('Scalar',
                                                                   StandardScaler())]),
                                                  ['Make', 'Model', 'Fuel Type',
                                                   'Transmission', 'Location',
                                                   'Color', 'Owner',
                                                   'Seller Type', 'Engine',
                                                   'Max Power', 'Max Torque',
                                                   'Drivetrain'])])),
                ('Linear_Regression', RandomForestRegressor())])

In [16]:
model.score(X_train,y_train)

0.9780561749079975

In [17]:
model.predict(X_test)

array([ 6181250.        ,   992389.99      ,  6651400.        ,
         815909.7       ,   713189.99      ,   380109.9       ,
         522289.69      ,  1294860.        ,   734579.94      ,
        4072620.        ,  4435579.98      ,   799639.99      ,
        2782510.        ,  4068120.        ,  3226830.        ,
        2502450.        ,  5374809.99      ,   422849.99      ,
         354069.94      ,   686259.96      ,   377429.98      ,
         906440.        ,  5809050.        ,  1605379.97      ,
        1523789.96      ,   550609.97      ,   298369.73      ,
         499440.        ,   576549.97      ,  2371020.        ,
         768759.97      ,   434189.94      ,  2997109.91      ,
         818989.93      ,   801389.98      ,  1430399.96      ,
        1066539.98      ,   566660.        ,   267319.94      ,
        1449759.97      ,  1159399.95      ,   339929.99      ,
        1317289.92      ,   472009.72      ,   472090.        ,
        1642689.98      ,   613329.95      ,   757779.96      ,
         435119.89      ,  1821639.96      ,   316179.99      ,
         300469.89      ,  2135269.92      ,   806369.88      ,
        2880449.99      ,  2357029.94      ,  2946979.97      ,
         459599.9       ,  2871389.96      ,  3162560.        ,
        4343509.99      ,  1871800.        ,  6020760.        ,
        1446159.98      ,  7585480.        ,  1327929.98      ,
        4995780.        ,  1011159.96      ,   466069.83      ,
         731769.96      ,  1156799.86      ,   848399.9       ,
        1196619.99      ,   757300.        ,  1320699.86      ,
         258339.99      ,   540060.        ,  8007650.        ,
         577430.        ,   393830.        ,   305009.98      ,
        5462060.        ,   659639.99      , 12133700.        ,
         568140.        ,  1394430.        ,   263940.        ,
        1473789.99      ,  3574249.98      ,   358039.94      ,
         663949.89      ,   731959.92      ,  2667760.        ,
        3237090.        ,   406749.9       ,   379859.93      ,
        1179499.94      ,   425929.74      ,   441439.88      ,
        2553300.        ,  1917390.        ,  2799240.        ,
         486499.91      ,  2778110.        ,   697229.99      ,
        3928860.        ,  6406460.        ,   593749.99      ,
         805499.97      ,   446239.89      ,   741549.95      ,
        1015199.98      ,   246649.95      ,   939469.91      ,
        1934429.96      ,   503959.57      ,   541590.        ,
        7247899.99      ,   272589.89      ,  3618640.        ,
         815910.        ,  4260539.98      ,   615150.        ,
        1261879.97      ,   398860.        ,  4399550.        ,
         744399.99      ,   448899.96      ,  3965760.        ,
         418029.85      ,  1486249.92      ,   979430.        ,
        2689000.        ,   645479.99      ,  1686659.95      ,
        2770740.        ,   564459.78      ,   423919.97      ,
        3650809.97      ,  1958339.97      ,   458849.84      ,
         281409.91      ,   419639.9       ,  4219360.        ,
         538889.67      ,   724459.99      ,   703489.97      ,
         577540.        ,   693589.98      ,   814470.        ,
        1283399.98      ,   260400.        ,   379459.98      ,
        2212359.99      ,  1264960.        ,   527219.99      ,
         626859.99      ,   791930.        ,  1079759.96      ,
        2950499.93      ,   343129.91      ,   852789.9       ,
         540870.        ,  6338210.        ,   453129.94      ,
        5011159.99      ,  1400169.96      ,  1118399.74      ,
         663230.        ,   598070.        ,   426369.92      ,
        1184500.        ,   273000.        ,  1155479.99      ,
        1800249.99      ,   335929.82      ,  2161569.9       ,
         545320.        ,   413439.96      ,   633380.        ,
         179569.97      ,  6855720.        ,   625769.99      ,
        3197110.        ,   422479.88      ,   720389.94      ,
        2639679.94      ,  2737889.93      ,   732819.94      ,
         608969.99      ,   880569.99      ,   366509.96      ,
         569990.        ,  6594220.        ,  3748900.        ,
         889629.95      ,   512339.98      ,  1945989.98      ,
        5630729.99      ,   422619.96      ,  3509709.97      ,
        3474379.99      ,   702809.89      ,   467369.88      ,
        5421710.        ,   362239.98      ,   706289.99      ,
        2517859.97      ,   728610.        ,   765079.93      ,
         388509.62      ,   374509.96      ,   635479.99      ,
         501680.        ,   356099.98      ,  2066289.98      ,
        2354819.77      ,   715760.        ,   431390.        ,
         839069.86      ,   419449.87      ,  1998369.98      ,
         725010.        ,   430939.87      ,  3645000.        ,
        2643900.        ,  3208230.        ,   399639.84      ,
        2172339.82      ,  1570800.        ,  4080370.        ,
        1172779.98      ,   871810.        ,   951759.99      ,
        1810519.97      ,   450609.78      ,   516620.        ,
        1368449.96      ,  1322429.86      ,  2484720.        ,
        2339119.96      ,  3424989.98      , 10331606.66666667,
        3151459.99      ,   711940.        ,   331180.        ,
        4836330.        ,   595610.        ,  1036160.        ,
        1965459.82      ,   506099.87      , 11023550.        ,
        1146799.95      ,  3291800.        ,  4815700.        ,
         319489.96      ,   574329.81      ,   245919.89      ,
         282969.91      ,  4214649.95      ,  1209900.        ,
         670239.94      ,   565760.        ,  4180110.        ,
         173189.99      ,  4485940.        ,  4048960.        ,
         354560.        ,  4578840.        ,  2572450.        ,
         411579.78      ,   935729.99      ,   570550.        ,
         818559.98      ,   290779.99      ,   955070.        ,
         369690.        ,   826779.99      ,   728589.83      ,
        1010959.99      ,   960849.94      ,   345379.99      ,
         927549.99      , 11336160.        ,   321809.97      ,
         507829.9       ,  1083989.96      ,  2531979.99      ,
         509169.99      ,   452310.        ,  1661539.97      ,
         870949.97      ,   587309.97      ,   328399.95      ,
         504789.97      ,  2333509.99      ,   456509.4       ,
         431159.88      ,   300629.99      ,  5350950.        ,
        6555300.        ,   733089.95      ,  3661889.99      ,
         732729.96      ,  1548150.        ,   672729.96      ,
         522629.75      ,  1780129.99      ,   641399.98      ,
         280399.99      ,   510839.84      ,  1333819.8       ,
         491659.83      ,   387159.94      ,  6039460.        ,
         240899.88      ,  4185100.        ,   567060.        ,
        6449900.        ,  2228540.        ,   871389.9       ,
         947179.99      ,   449259.98      ,  1310899.99      ,
        2851589.96      ,  1600719.98      ,   853489.87      ,
        2232749.98      ,   427629.91      ,  1271099.97      ,
         288539.94      ,  5317660.        ,  1601239.99      ,
         518529.99      ,   913999.99      ,   305079.99      ,
         289449.96      ,  2820620.        ,  1680249.99      ,
        1056990.        ,  4472400.        ,  4596213.32333333,
        2262009.98      ,   532959.93      ,  6124860.        ,
        1240250.        ,   449929.87      ,   350499.94      ,
         748180.        ,   453819.99      ,   483509.94      ,
         615470.        ,  1180139.93      ,  1997029.98      ,
         273019.9       ,   418379.94      ,   515269.9       ,
        1077070.        ,   847899.99      ,   283429.99      ,
         725539.97      ,  3776020.        ,   596700.        ,
        4660090.        ,  1952079.96      ,   507139.97      ,
         577259.87      ,  4740040.        ,  4870090.        ,
        5076329.98      ,  6636750.        ,   838279.88      ,
         533759.99      ,  1233589.99      ,  3283660.        ,
         187320.        ,   288439.99      ,  3307589.99      ,
        8459400.        ,   439859.97      ,   618409.92      ,
         590109.97      ,  1087399.97      ,  1158159.67      ,
        3944560.        ,   251040.        ,   542419.93      ,
         483400.        ,  2068609.96      ,   520190.        ,
        4331443.32333333,  3465170.        ,   657239.99      ,
        4937750.        ,  1459779.99      ,   960399.91      ,
        2037839.72      ,   377749.85      ,  2784359.97      ,
        2427899.98      ,  5205600.        ,  2168720.        ,
         736430.        ,  1261349.63      ,  4757700.        ,
        2721890.        ,  1117079.99      ,  1698219.93      ,
        1974389.97      ,   639409.97      ,   706949.9       ,
         288849.9       ,  4293520.        ,  2437090.        ,
         381009.8       ,   589589.99      ,   645109.98      ,
        1487229.97      ,   301519.97      ,   495129.98      ,
         536989.97      ,   467829.68      ,   706829.98      ,
         643429.95      ,   308259.92      ,   369779.97      ,
        2451109.93      ,  1194859.96      ,  4037140.        ,
         465289.89      ,   314589.94      ,   789539.86      ,
         354929.99      ,   537900.        ,   273620.        ,
         817680.        ,  1119239.99      ,  3249139.99      ,
         443699.69      ,  1146500.        ,   827229.98      ,
         562479.85      ,   476649.43      ,  1455340.        ,
         482199.96      ,   663819.99      ,   463279.91      ,
         364469.99      ,   810920.        ,   864799.97      ,
         698969.95      ,   452079.86      ,  1085149.96      ,
        3861410.        ,  2085899.97      ,  2354899.99      ,
        1150049.98      ,   314629.98      ,   701849.94      ,
         774609.99      ,   259459.99      ,   540729.97      ,
         523710.        ,  3815640.        ,   653310.        ,
         482889.99      ,   196899.98      ,  1663649.94      ,
        3863040.        ,  1532449.9       ,   581389.99      ,
        4007360.        ,  1543019.99      ,   327779.97      ,
        1206419.99      ,   996229.97      ,   566609.63      ,
         613850.        ,   581079.96      ,   507639.95      ,
         756069.95      ,   278179.91      ,  1730969.67      ,
         880569.99      ,   900439.97      ,  1639309.91      ,
         611900.        ,   421949.97      ,   192129.94      ,
        3791490.        ,   311169.98      ,   722070.        ,
         567810.        ,   361949.99      ,  2109019.97      ,
        1012899.99      ,  6384293.33333333,   673600.        ,
        2532659.99      ,  1055869.97      ,  1754329.91      ,
         578729.89      ,   630220.        ,  9430800.        ,
         440259.94      ,   798830.        ,  2295209.98      ,
         693859.97      ,   495859.94      ,  1909970.        ,
         445499.99      ,   975589.99      , 11915850.        ,
         881390.        ,  6222790.        ,  2083299.99      ,
        1869829.94      ,   431529.77      ,   609880.        ,
        1543239.99      , 11009850.        ,  1553250.        ,
        1138249.98      ,   435079.83      ,  2954989.99      ,
         340239.99      ,   962099.81      ,  4775240.        ,
         568710.        ,   592630.        ,  1649189.94      ,
         631000.        ,   422259.91      ,   418039.94      ,
        2692659.97      ,   668739.99      ,  1174539.97      ,
         365279.97      ,  1973809.92      ,   487519.81      ,
        2116379.95      ,   462409.91      ,  1901209.95      ,
         920900.        ,   416039.79      ,   561179.95      ,
         274969.97      ,  2159029.99      ,  2505399.98      ,
         249209.97      ,  1271670.        ,  3990683.33333333,
         706340.        ,   416009.94      ,   190500.        ,
         754650.        ,  2304090.        ,   971650.        ,
        2775489.99      ,   406539.88      ,  2387159.99      ,
        1591600.        ,   609149.99      ,  1287449.98      ,
        2909609.96      ,  4051890.        ,  1188259.94      ,
        6535550.        ,  3634959.98      ,  3010609.99      ,
        1538610.        ,   853410.        ,   305129.7       ,
         663300.        ,  4971960.        ,   384530.        ,
         268549.97      ,  2993380.        ,   297699.8       ,
         552789.9       ,  1655850.        ,   577990.        ,
        2922070.        ,   810660.        ,  1956729.78      ,
         439009.96      ,  1201789.98      ,  1080239.98      ,
        1071629.93      ,   447449.99      ,   667240.        ,
         728449.99      ,   868929.92      ,  1058349.99      ,
         953069.99      ,  2316259.96      ,   376759.99      ,
         523749.96      ,   814269.98      ,   480479.95      ,
         282049.9       ,  5272950.        ,   776299.96      ,
         833689.98      ,  5442040.        ,   909599.87      ,
         425829.8       ,   269599.94      ,   435630.        ,
         796830.        ,   914720.        ,  2388000.        ,
         642369.95      ,  3666140.        ,  2292209.99      ,
         853100.        ,   583200.        ,  1653479.98      ,
         727059.95      ])